name: Check dual-stack behavior

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  dual-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build --no-link .#checks.x86_64-linux.dual-stack
